import {
  type WorkspaceSnapshot,
  workspaceSnapshotSchema,
} from "@auria/contracts";

const objective = (enabled: boolean, intensity: number, target: string) => ({
  enabled,
  intensity,
  target,
});

export const createDemoWorkspaceSnapshot = (): WorkspaceSnapshot =>
  workspaceSnapshotSchema.parse({
    id: "workspace-auria-hub",
    name: "Auria Hub",
    repositoryName: "auria-control-plane",
    repositoryProvider: "github",
    branch: "main",
    localRepositoryPath: null,
    mode: "hybrid",
    vision:
      "Operate as an autonomous engineering layer that improves repositories under explicit risk, budget and governance controls.",
    planName: "Builder Beta",
    objectives: {
      quality: objective(true, 82, "Reduce noisy regressions and improve maintainability."),
      security: objective(true, 76, "Harden sensitive flows before release branches are cut."),
      technicalDebt: objective(true, 88, "Pay down fragile modules with small, safe edits."),
      dependencies: objective(true, 63, "Keep patch releases current with low-risk updates."),
      coverage: objective(true, 58, "Raise targeted test confidence on hot paths."),
      documentation: objective(true, 64, "Keep operational knowledge current and searchable."),
      performance: objective(false, 42, "Only optimize when evidence shows a bottleneck."),
      innovation: objective(true, 51, "Suggest viable product improvements with low implementation risk."),
      research: objective(true, 69, "Use external research selectively and keep it auditable."),
    },
    modelRouter: {
      planning: {
        primary: "gpt-5",
        fallback: "gpt-5-mini",
        externalTools: true,
        depth: "deep",
        parallelism: 3,
        costPolicy: "balanced",
        latencyPolicy: "balanced",
      },
      implementation: {
        primary: "gpt-5-codex",
        fallback: "gpt-5-mini",
        externalTools: false,
        depth: "balanced",
        parallelism: 5,
        costPolicy: "balanced",
        latencyPolicy: "fast",
      },
      research: {
        primary: "gpt-5",
        fallback: "gpt-5-mini",
        externalTools: true,
        depth: "deep",
        parallelism: 4,
        costPolicy: "premium",
        latencyPolicy: "deliberate",
      },
      review: {
        primary: "gpt-5",
        fallback: "gpt-5-mini",
        externalTools: false,
        depth: "deep",
        parallelism: 2,
        costPolicy: "balanced",
        latencyPolicy: "balanced",
      },
      risk: {
        primary: "gpt-5",
        fallback: "gpt-5-mini",
        externalTools: false,
        depth: "deep",
        parallelism: 2,
        costPolicy: "premium",
        latencyPolicy: "deliberate",
      },
      memory: {
        primary: "gpt-5-mini",
        fallback: "gpt-5-nano",
        externalTools: false,
        depth: "focused",
        parallelism: 2,
        costPolicy: "efficient",
        latencyPolicy: "fast",
      },
    },
    policies: {
      maxLinesPerMission: 320,
      maxLinesPerFile: 120,
      maxFilesTouched: 5,
      allowedPaths: ["apps/", "packages/", "docs/", "supabase/"],
      blockedPaths: ["node_modules/", "dist/", ".git/"],
      criticalPaths: ["apps/desktop/src/main/", "supabase/migrations/"],
      allowedFileTypes: [".ts", ".tsx", ".sql", ".md", ".json", ".css"],
      blockedFileTypes: [".env", ".pem", ".key", ".lock"],
      maxConcurrentAgents: 5,
      monthlyBudgetUsd: 750,
      executionWindow: "Mon-Fri 08:00-20:00 local",
      autonomyMode: "guarded_autonomy",
      requireHumanReviewAbove: "high",
    },
    knowledgeBase: [
      {
        id: "doc-1",
        name: "product-context.md",
        kind: "product",
        status: "ready",
        version: "v3",
        lastUpdatedAt: "2026-03-13T18:00:00.000Z",
        useForAnalysis: true,
        useForInnovation: true,
      },
      {
        id: "doc-2",
        name: "architecture-map.md",
        kind: "architecture",
        status: "ready",
        version: "v2",
        lastUpdatedAt: "2026-03-12T09:30:00.000Z",
        useForAnalysis: true,
        useForInnovation: false,
      },
      {
        id: "doc-3",
        name: "ops-runbook.md",
        kind: "operations",
        status: "processing",
        version: "v5",
        lastUpdatedAt: "2026-03-14T11:00:00.000Z",
        useForAnalysis: true,
        useForInnovation: false,
      },
      {
        id: "doc-4",
        name: "roadmap-signals.md",
        kind: "roadmap",
        status: "stale",
        version: "v1",
        lastUpdatedAt: "2026-02-01T14:10:00.000Z",
        useForAnalysis: false,
        useForInnovation: true,
      },
    ],
    agents: [
      {
        id: "agent-planner",
        name: "Planner",
        role: "planner",
        state: "analyzing",
        currentMissionId: "mission-1",
        currentMissionTitle: "Shrink auth onboarding complexity",
        risk: "moderate",
        costUsd: 18.6,
      },
      {
        id: "agent-risk",
        name: "Gate",
        role: "risk",
        state: "validating",
        currentMissionId: "mission-4",
        currentMissionTitle: "Review migration safety rails",
        risk: "high",
        costUsd: 11.8,
      },
      {
        id: "agent-research",
        name: "Research",
        role: "research",
        state: "researching",
        currentMissionId: "mission-3",
        currentMissionTitle: "Compare semantic memory chunking patterns",
        risk: "low",
        costUsd: 14.2,
      },
      {
        id: "agent-security",
        name: "Security",
        role: "security",
        state: "executing",
        currentMissionId: "mission-2",
        currentMissionTitle: "Patch unsafe session refresh flow",
        risk: "high",
        costUsd: 22.9,
      },
      {
        id: "agent-memory",
        name: "Memory",
        role: "memory",
        state: "idle",
        currentMissionId: null,
        currentMissionTitle: null,
        risk: "low",
        costUsd: 6.1,
      },
    ],
    missions: [
      {
        id: "mission-1",
        title: "Shrink auth onboarding complexity",
        objective: "quality",
        status: "analyzing",
        risk: "moderate",
        summary:
          "Map the onboarding flow and isolate view state from identity bootstrapping.",
        touchedFiles: ["apps/desktop/src/renderer/features/onboarding/"],
        changedLines: 96,
        estimatedCostUsd: 24.5,
        assignedAgents: ["Planner", "Review"],
        validations: ["ui smoke", "typecheck"],
        blockedReason: null,
        startedAt: "2026-03-14T10:20:00.000Z",
      },
      {
        id: "mission-2",
        title: "Patch unsafe session refresh flow",
        objective: "security",
        status: "executing",
        risk: "high",
        summary:
          "Move token refresh orchestration behind a stricter gate and reduce renderer exposure.",
        touchedFiles: [
          "apps/desktop/src/main/",
          "apps/desktop/src/preload/",
          "packages/contracts/src/index.ts",
        ],
        changedLines: 118,
        estimatedCostUsd: 41.2,
        assignedAgents: ["Security", "Gate"],
        validations: ["ipc contract tests", "typecheck"],
        blockedReason: null,
        startedAt: "2026-03-14T09:50:00.000Z",
      },
      {
        id: "mission-3",
        title: "Compare semantic memory chunking patterns",
        objective: "research",
        status: "researching",
        risk: "low",
        summary:
          "Evaluate hybrid chunking for code, docs and mission artifacts before embeddings are stored.",
        touchedFiles: ["docs/", "supabase/migrations/"],
        changedLines: 48,
        estimatedCostUsd: 17.9,
        assignedAgents: ["Research"],
        validations: ["source log"],
        blockedReason: null,
        startedAt: "2026-03-14T10:10:00.000Z",
      },
      {
        id: "mission-4",
        title: "Review migration safety rails",
        objective: "technicalDebt",
        status: "validating",
        risk: "high",
        summary:
          "Introduce idempotent SQL and safer defaults for policy and memory tables.",
        touchedFiles: ["supabase/migrations/0001_init.sql"],
        changedLines: 131,
        estimatedCostUsd: 28.4,
        assignedAgents: ["Gate", "Planner"],
        validations: ["migration diff", "sql lint"],
        blockedReason: null,
        startedAt: "2026-03-14T08:30:00.000Z",
      },
      {
        id: "mission-5",
        title: "Refresh dependency policy thresholds",
        objective: "dependencies",
        status: "discovered",
        risk: "low",
        summary:
          "Tune patch-only updates so low-risk packages can be auto-approved.",
        touchedFiles: ["packages/domain/src/services/"],
        changedLines: 32,
        estimatedCostUsd: 9.6,
        assignedAgents: ["Dependency"],
        validations: ["typecheck"],
        blockedReason: null,
        startedAt: "2026-03-14T11:05:00.000Z",
      },
      {
        id: "mission-6",
        title: "Backfill worker test harness",
        objective: "coverage",
        status: "review",
        risk: "moderate",
        summary:
          "Add contract-based tests around worker planning and policy enforcement.",
        touchedFiles: ["apps/local-worker/src/", "packages/domain/src/services/"],
        changedLines: 88,
        estimatedCostUsd: 18.1,
        assignedAgents: ["Test", "Review"],
        validations: ["vitest", "typecheck"],
        blockedReason: null,
        startedAt: "2026-03-14T07:40:00.000Z",
      },
      {
        id: "mission-7",
        title: "Document policy builder defaults",
        objective: "documentation",
        status: "completed",
        risk: "low",
        summary:
          "Capture why each guardrail ships with its default ceiling and review threshold.",
        touchedFiles: ["docs/architecture.md"],
        changedLines: 26,
        estimatedCostUsd: 7.2,
        assignedAgents: ["Docs"],
        validations: ["docs review"],
        blockedReason: null,
        startedAt: "2026-03-13T16:15:00.000Z",
      },
      {
        id: "mission-8",
        title: "Prototype repository innovation lane",
        objective: "innovation",
        status: "blocked",
        risk: "critical",
        summary:
          "Innovation ideas are touching billing and org policy. Human approval is required.",
        touchedFiles: ["apps/desktop/src/renderer/features/billing/"],
        changedLines: 144,
        estimatedCostUsd: 36.7,
        assignedAgents: ["Innovation", "Gate"],
        validations: ["policy gate"],
        blockedReason: "Touches a billing surface and exceeds the human review threshold.",
        startedAt: "2026-03-14T09:15:00.000Z",
      },
    ],
    reviewQueue: [
      {
        id: "review-1",
        missionId: "mission-6",
        decision: "pending",
        summary: "Worker plan tests are ready for human review before merge.",
        beforeAfter:
          "Before: worker planning had no executable contract checks. After: policy thresholds and gating are tested.",
        risk: "moderate",
        filesTouched: [
          "apps/local-worker/src/domain/risk-gate.ts",
          "packages/domain/src/services/policy-guards.test.ts",
        ],
        researchSources: [],
        validations: ["vitest", "typecheck"],
      },
      {
        id: "review-2",
        missionId: "mission-4",
        decision: "needs_changes",
        summary: "Migration is structurally sound but needs smaller blast radius defaults.",
        beforeAfter:
          "Before: broad table defaults. After: safer constraints, but one index still needs review.",
        risk: "high",
        filesTouched: ["supabase/migrations/0001_init.sql"],
        researchSources: [],
        validations: ["sql lint"],
      },
      {
        id: "review-3",
        missionId: "mission-2",
        decision: "pending",
        summary: "Security patch improves token flow isolation and reduces renderer trust.",
        beforeAfter:
          "Before: refresh logic leaked orchestration decisions to the renderer. After: preload exposes a narrow bridge.",
        risk: "high",
        filesTouched: [
          "apps/desktop/src/main/index.ts",
          "apps/desktop/src/preload/index.ts",
        ],
        researchSources: [],
        validations: ["ipc contract tests", "typecheck"],
      },
    ],
    memoryInsights: [
      {
        id: "memory-1",
        category: "errors",
        title: "Renderer state grows brittle when auth bootstrap owns UI concerns",
        summary:
          "Keep auth orchestration in application services and pass only stable view state to components.",
        strength: "stable",
      },
      {
        id: "memory-2",
        category: "hotspots",
        title: "Supabase migrations are a critical zone",
        summary:
          "Any SQL touching memory or billing requires a gate review and idempotent migration guards.",
        strength: "critical",
      },
      {
        id: "memory-3",
        category: "patterns",
        title: "Small policy-driven edits land faster than broad refactors",
        summary:
          "Keep missions under five files and under one hundred twenty lines when possible.",
        strength: "stable",
      },
      {
        id: "memory-4",
        category: "recommendations",
        title: "Knowledge intake should stay close to mission planning",
        summary:
          "Docs that are fresh and linked to a workspace improve innovation and review quality.",
        strength: "emerging",
      },
    ],
    billing: {
      planName: "Builder Beta",
      cycleLabel: "Mar 1 - Mar 31",
      spendUsd: 212.7,
      limitUsd: 750,
      repositoriesUsed: 1,
      repositoriesLimit: 3,
      maxAgents: 5,
    },
  });
